services:
  nginx-1:
    image: nginx:alpine
    container_name: frontend_webdemo-1_mvps2
    restart: unless-stopped

    volumes:
      - ./html:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - php
    networks:
      - app-network
      - frontend 
    ports:
      - 9001:80

  php:
    build: .
    container_name: php_webdemo-1_mvps2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
    networks:
      - app-network
  
  mysql:
    image: mariadb:10.11
    restart: unless-stopped
    container_name: db_webdemo-1_mvps2

    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=demo1234
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: phpmyadmin_webdemo-1_mvps2
    environment:
      - PMA_HOST=mysql
      # - PMA_USER=root
      # - PMA_PASSWORD=demo1234
    ports:
      - 9002:80
    networks:
      - frontend
      - app-network

networks:
  app-network:
    driver: bridge
  frontend:
    external: true
